### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jacopocolo** [PaulKElliott/spin-controls#12]
Hi, is there intentionally NOT a license for this module? 

I started working on a fork for a project I'm working on of the spincontrol.js module to allow basic `translate` and `scale` of the object on top of the rotation. But of course if the intention is NOT to allow modifications, I'll stop working on it. 

Just to be clear: I'm a threejs beginner so my intention is not to merge back my changes into this repo. But without a license I'm not even sure if it's okay to publish and distribute my fork. 

And thanks for the amazing work you've done with this module.

**Comment by PaulHax** [comment]
Hello, please feel free to modify.  If the MIT will do it for you, I will add.

**Comment by jacopocolo** [comment]
Thank you! MIT will do very fine!

**Comment by PaulHax** [comment]
MIT license added.  I look forward following your project.
