### ISSUE TITLE
I can not set cameraSpinControls.enableRotate but i find a other way to do this

### ISSUE THREAD

**Issue by Yty202020** [PaulKElliott/spin-controls#16]
hi brother  im a chinese amateur coder and my english is so poor
i am glad to find your nice puglin 
but when i use the CameraSpinControls.js and want to disable the rotatecontrol for camera 
i find it didn't work then i read your code  the  member-var 'enableRotate' no effect
===================
but  i find  change this line i could stop the rotate
scope.spinControl.rotateSensitivity *= 0; // Negated it to pull camera around sphere as if sphere is fixed.

**Comment by PaulHax** [comment]
Thank you for reporting this bug and kudos for finding a workaround.  Another workaround option:
`cameraSpinControl.spinControl.enabled = false;`
