### ISSUE TITLE
how to limit the object rotation

### ISSUE THREAD

**Issue by Yty202020** [PaulKElliott/spin-controls#18]
hi brother 
i want to limit the obj-3d spin
like the OrbitControls.max(min)AzimuthAngle、max(min)PolarAngle
i think may change  this part to add limit
`
		return function applyVelocity() {

			timeStamp = performance.now();
			deltaTime = ( timeStamp - _lastVelTime ) / 1000.0;
			_lastVelTime = timeStamp;

			if( _this.spinAxisConstraint ) {

				normalizedAxis.copy( _this.spinAxisConstraint );
        deltaAngle = normalizedAxis.dot( _angularVelocity ) ;

      } else {

				normalizedAxis.copy( _angularVelocity );
				deltaAngle = _angularVelocity.length();

			}

			if ( deltaAngle && deltaTime ) {

				normalizedAxis.normalize();
        console.log(deltaAngle);
        quat.setFromAxisAngle( normalizedAxis, deltaAngle * deltaTime * _this.rotateSensitivity );

				_this.object.quaternion.normalize();
				_this.object.quaternion.premultiply(quat);

				// using small-angle approximation cos(x/2) = 1 - x^2 / 8

				if ( 8 * ( 1 - _lastQuaternion.dot( _this.object.quaternion ) ) > _EPS) {

					_this.dispatchEvent( changeEvent );

					_lastQuaternion.copy( _this.object.quaternion );

				}

			}

		};
` 
But im just a ui-d .
I try to learn "quaternion" . emmm i want to die

**Comment by PaulHax** [comment]
Hehe, I don't understand quaternions either.  But convert to a rotation representation you understand and apply the constraint at the application code level after the update() call.  
```
spinControl.update();
const objectOri = new THREE.Euler( 0, 0, 0, 'YXZ' );;
objectOri.setFromQuaternion(spinControl.object.quaternion);
if (objectOri.y > 1) {
	objectOri.y = 1; // a silly constraint
}
spinControl.object.quaternion.setFromEuler(objectOri);
```

**Comment by Yty202020** [comment]
thank a lot
