### ISSUE TITLE
when i use camera pan it may interact with dolly controls

### ISSUE THREAD

**Issue by Yty202020** [PaulKElliott/spin-controls#19]
https://user-images.githubusercontent.com/35088114/122936661-e9c40600-d3a3-11eb-9928-db3a46334755.mp4

when two fingers were close TOGETHER, to pan the camera, the scene will shake. But if the distance of the fingers were longer, things seemed to be OK.

**Comment by PaulHax** [comment]
Good find.  2+ fingers also zoom/dolly and "spin."  Looks like some threshold/damping may be needed when fingers are close.

**Comment by Yty202020** [comment]
copy that.
i change lower the zoomSpeed = 0.4; The problem is solved.
thanks alot
