### ISSUE TITLE
Rotate about point clicked under cursor

### ISSUE THREAD

**Issue by raffdp** [PaulKElliott/spin-controls#3]
If you zoom and pan to an area of the scene, can the centre of rotation be the point clicked under the mouse/touch?

**Comment by PaulHax** [comment]
I like where you going with that!  With some changes, the application can move the trackball location.  Say to a intersection point with a model.

Checkout the new branch `off-center` and the `example_camera_spin_pointer_centered.html` file.

**Comment by raffdp** [comment]
Wow! That feature is just what I was looking for in a controller so long!! Amazing.

It works so well on a touch screen. Very intuitive when inspecting a scene. I have another question but will open a separate issue for it.

**Comment by PaulHax** [comment]
Made a few more tweaks and incorporated into the main branch.  Thanks for the inspiration.  See any funny stuff, let me know.
