### ISSUE TITLE
Rotate scene about camera Z with 2 fingers

### ISSUE THREAD

**Issue by raffdp** [PaulKElliott/spin-controls#5]
Would it be possible to use a two finger twist gesture to rotate along the camera view z, like the "pinch + rotate" example here http://alloyteam.github.io/AlloyFinger/. So in a plane parallel to the screen plane, and the rotate in x,y about z only.

**Comment by raffdp** [comment]
Actually, the center of rotation would probably be the center between your two fingers, or the last rotation center point if no point was hit on an object between your two fingers, or if either finger hit a point on the object, and the first finger to hit would be the rotation center.

Like a simple compass for drawing a circle.

**Comment by PaulHax** [comment]
I dig it. 

Keep this up, we get the full Google Maps touch action going.

**Comment by raffdp** [comment]
Does this work with an Orthographic camera?

**Comment by raffdp** [comment]
Perfect!
